<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DoctrineDataFixtureModule\Command\ImportCommand'  => __DIR__ . '/src/DoctrineDataFixtureModule/Command/ImportCommand.php',
    'DoctrineDataFixtureModule\Service\FixtureFactory' => __DIR__ . '/src/DoctrineDataFixtureModule/Service/FixtureFactory.php',
    'DoctrineDataFixtureModule\Module'                 => __DIR__ . '/src/DoctrineDataFixtureModule/Module.php',
);